# Generated by Django 4.1 on 2022-12-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("a_idx", models.AutoField(primary_key=True, serialize=False)),
                ("a_id", models.CharField(blank=True, max_length=20, null=True)),
                ("a_pw", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={"db_table": "admin", "managed": True,},
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("p_code", models.CharField(blank=True, max_length=30, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("addr", models.CharField(blank=True, max_length=300, null=True)),
                ("religion", models.CharField(blank=True, max_length=10, null=True)),
                ("scholar", models.CharField(blank=True, max_length=15, null=True)),
                ("sex", models.CharField(blank=True, max_length=10, null=True)),
                ("job", models.CharField(blank=True, max_length=20, null=True)),
                ("salary", models.BigIntegerField(blank=True, null=True)),
                ("property", models.BigIntegerField(blank=True, null=True)),
                ("debt", models.BigIntegerField(blank=True, null=True)),
                ("re_marry", models.IntegerField(blank=True, null=True)),
                ("drink", models.IntegerField(blank=True, null=True)),
                ("smoke", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("family", models.CharField(blank=True, max_length=100, null=True)),
                ("child", models.IntegerField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=5, null=True)),
                ("matching", models.IntegerField(blank=True, default=0, null=True)),
                ("event", models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={"db_table": "members", "managed": True,},
        ),
    ]
